# Site
title:              Çiğdem Doğan
bio:                'Çiğdem Doğan Sufukun Gözünden'
description:        "Çiğdem Doğan Sufukun Gözünden"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
#disqus_shortname:   default

# Social
analytics-id:       "default"
#twitter:            default
#facebook:           default
instagram:          sufukguler
github:             sufuk

# personal
location:           Istanbul, Bostanci
phone:              530-329-0033
email:              sufuk@ieee.org # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg2.png
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

webmaster_verifications:
  google: <meta name="google-site-verification" content="rTnWjnntpWhBhb5G4woL5YVLWPofUq6IISJ1VeGdQbg" />
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234
# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
